language: android
android:
  components:
    # U se the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.0.1

    # The SDK version used to compile your project
    - android-21
